#DatosEstaticos.py
def listarProductos():
    print("Lista de productos")
    print("1. Azucar")
    print("2. Harina")
    print("3. Manteca/Puerco")
    print("4. Manteca/Vegetal")
    print("5. Termico #32 L")
    print("6. Termico #32 1/2")
    print("7. Termico #16")
    print("8. Termico #12")
    print("9. Termico #10")
    print("10. Termico #4j4")
    print("11. Termico #6j6")
    print("12. Arroz Saman")
    print("13. Arroz Morelos")
    print("14. Frijol")
    print("15. Alpiste/Simple")
    print("16. Alpiste/Compuesto")
    print("17. Charrola 07")
    print("18. Charrola 855")
    print("19. Charrola 066")
    print("20. Aceite L1/2")
    print("21. Aceite L")
    print("22. Aceite 1/2")
    print("23. Canoil")
    print("24. Soya Plus")
    print("25. Nutrioli")
    print("26. Aceite 5L")
    print("27. Levadora")
    print("28. Galletas/Mexicanas")
    print("29. Maiz/Quebrado")
    print("30. Maiz/Entero")
    
    
    